### ISSUE TITLE
New Google analytics version  not working 

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#39]
Suggestions?

It seems an error related to metrics.
I've tried 

```
cd /srv/ontoportal/ncbo_cron/
bin/ncbo_ontology_process -a -t run_metrics 
```
and 

`oprestart`

but:

<img width="1507" alt="Screenshot 2024-02-05 alle 11 42 59" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/95cbf695-3bf1-4e1a-8cd8-29ae1fe8435d">

This is the content of `appliance.log`

```
F, [2024-02-05T10:41:59.745621 #5961] FATAL -- :   
MultiJson::ParseError (Problem retrieving:
/analytics?month=1&year=2024

Error: Problem loading json
<h1>Internal Server Error</h1>
/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/multi_json-1.15.0/lib/multi_json/adapters/oj.rb:34:in `load'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/multi_json-1.15.0/lib/multi_json/adapters/oj.rb:34:in `load'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/multi_json-1.15.0/lib/multi_json/adapter.rb:21:in `load'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:122:in `load'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/http.rb:290:in `load_json'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/http.rb:157:in `object_from_json'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/middleware/faraday-object-cache.rb:94:in `block in call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/faraday-2.0.1/lib/faraday/response.rb:42:in `on_complete'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/middleware/faraday-object-cache.rb:63:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/middleware/faraday-last-updated.rb:16:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/middleware/faraday-slices.rb:16:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/middleware/faraday-user-apikey.rb:24:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/faraday-2.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/faraday-2.0.1/lib/faraday/connection.rb:445:in `run_request'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/faraday-2.0.1/lib/faraday/connection.rb:200:in `get'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/http.rb:68:in `get'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/analytics.rb:33:in `get'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_api_ruby_client-d0e5d81a08d0/lib/ontologies_api_client/analytics.rb:16:in `last_month'
	/srv/ontoportal/bioportal_web_ui/releases/20231121235821/app/controllers/home_controller.rb:51:in `index'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:215:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actiontext-7.0.3/lib/action_text/rendering.rb:20:in `with_renderer'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actiontext-7.0.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:151:in `process'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionview-7.0.3/lib/action_view/rendering.rb:39:in `process'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:188:in `dispatch'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:251:in `dispatch'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `each'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `serve'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/turnout-2.5.0/lib/rack/turnout.rb:25:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/rack/browser_monitoring.rb:38:in `traced_call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/static.rb:161:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/tempfile_reaper.rb:15:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/etag.rb:27:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/conditional_get.rb:27:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:266:in `context'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:260:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/cookies.rb:697:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:40:in `call_app'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:25:in `block in call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `block in tagged'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:38:in `tagged'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `tagged'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:25:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.1.1/lib/mini_profiler.rb:260:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/engine.rb:530:in `call'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/railtie.rb:226:in `public_send'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/railties-7.0.3/lib/rails/railtie.rb:226:in `method_missing'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
	/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
	/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
	/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
	/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
	/srv/ontoportal/bioportal_web_ui/shared/bundle/ruby/2.7.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:434:in `block in thread_block_with_current_transaction'):
  
app/controllers/home_controller.rb:51:in `index'
```

**Comment by syphax-bouazzouni** [comment]
You can find a temporary hotfix here #40, 
This is related to the new version of Google Analytics that is no longer compatible with your version of code; we did an update in our code to fix that, you can see details of how we did it here  https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/118
And some documentation here https://doc.jonquetlab.lirmm.fr/doc/how-google-analytics-r36anTZshi

**Comment by syphax-bouazzouni** [comment]
Migration to the new version of Google Analytics is done (https://ecoportal.lifewatchdev.eu/statistics)
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/6b7e43e2-2243-4699-95b2-a00000cf5962)
